### ISSUE TITLE
Timeline control uses Sprite and Frame

### ISSUE THREAD

**Issue by sraboy** [sraboy/skaa_editor#33]
The Timeline shouldn't use SkaaGameDataLib at all. It should have, at most, just a collection of the bitmaps. Maybe Timeline could use a framed Bitmap format and SkaaEditorUI would convert to that before setting the property. 

Refactoring SkaaGameDataLib required changes in Timeline even though it's irrelevant. It's no longer well-tested.

**Comment by Olreich** [comment]
Pushed an initial commit to refactor_timeline_control that eliminates the dependency and makes the TimelineControl a little more obvious when reading. Still needs another round of clean-up, but technically it works.

I may have missed some functionality or caused a non-update at some point as well.

When animating the TimelineControl, the main image also animates. I left this as is, since it seemed useful.

**Comment by Olreich** [comment]
New commits, should fix last of the crashes and corrects the animation system to be better.

**Comment by sraboy** [comment]
Closed by Pull Request #35. Ended up in merge hell, which was resolved with 38234be0c3455e62a2e8f56ab88fb4813e26805c and 771c71149de57a8efc642d2e37966087f9b52944 to get my own working branch back in line with master.
